### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Otojon** [zidansec/CloudPeler#7]
i did the same thing on my kali:    `$./crimeflare.php example.com` but didn't work. It progressed until 100 % and nothing happened :)

**Comment by spmedia** [comment]
Its pretty much a skiddie app. It does not work any longer because where it pulls info from (https://crimeflare.herokuapp.com/) is down. This script will not work until that comes online (if ever again) or OP changes it to use another source.

Just use https://shadowcrypt.net/tools/cloudflare for now.

**Comment by OtojonKhudayarov** [comment]
> 

good , thanks

**Comment by zidansec** [comment]
This project has been discontinued, no longer working. Many people use this tool for personal needs and make money. However, as the author who provides this tool for free, it is difficult for me to develop the project due to lack of funds, Maybe later this project will run again.

**Comment by zidansec** [comment]
> i did the same thing on my kali: `$./crimeflare.php example.com` but didn't work. It progressed until 100 % and nothing happened :)

That's because this project has been terminated. It won't work anymore.
